### ISSUE TITLE
Reference markdown inside JSON

### ISSUE THREAD

**Issue by rflnogueira** [Prototype-Group/generator-prototype#35]
Hello,

How do you reference a markdown file from inside a json data file?

For example, given I have two files homepage.json and body.md, how do I reference body.md inside homepage.json??

Cheers,

Rafael.

**Comment by Sebastian-Fitzner** [comment]
Hi,

your problem is really easy to solve. 

But first, I would suggest you rename your `body.md` to `hompage.md`. In general body is reserved and used in your templates. It should not produce any errors when you leave it like that...

Now to your problem. At first you should know there is a helper called `{{md}}`. This helper can get one argument: The path (from your root) to your md file: 

**Example:**

``` hbs
{{md "resources/data/homepage/homepage.md"}}
```

When you want to save your path in a json file it might look like that: 

```json
{
	"rteMd": "resources/data/homepage/homepage.md"
}
```

Now you can simply use this json file to render your md file: 
 
``` hbs
{{#with homepage}}
        {{md rteMd}}
{{/with}}
```
or
``` hbs
{{md homepage.rteMd}}
```

When you need a more detailled working example. just take a look into my provided bower component [pg-components](https://github.com/Sebastian-Fitzner/pg-components/tree/master/components/rte) or visit the repo of our [pg website](https://github.com/Sebastian-Fitzner/pg-website/) and look at 
- `resources/templates/partials/components/article` 
- `resources/templates/pages/index.hbs`
- `resources/data/pages/homepage.json`
- `resources/data/pages/index.md`

Good luck ;)

**Comment by rflnogueira** [comment]
Hello Sebastian,

Thanks a lot for the answer!

Maybe you can add an example json to: http://www.prototype-generator.com/templating-in-pg/template-data.html ?

Thank you for the help!

**Comment by Sebastian-Fitzner** [comment]
Good idea. Will update the page...
