### ISSUE TITLE
grunticon vs dr-svg-sprites?

### ISSUE THREAD

**Issue by ldexterldesign** [Prototype-Group/generator-prototype#36]
Hey,

Just wondering if there's a massive difference between the following?:
* https://github.com/filamentgroup/grunticon
* https://github.com/drdk/grunt-dr-svg-sprites

https://github.com/drdk/grunt-dr-svg-sprites reads (although the documentation is vague IMO) as though it offers SVG creation (i.e. shapes), which https://github.com/filamentgroup/grunticon doesn't

What does https://github.com/drdk/grunt-dr-svg-sprites offer that https://github.com/filamentgroup/grunticon doesn't?

Yours hopefully,

**Comment by rasmusfl0e** [comment]
Dr-svg-sprites combines multiple SVGs into a single SVG spritesheet.

On the upside the spritesheets are just referenced as standard non-blocking background-images in the generated stylesheets - no javascript required (though you are free to use `.svg` or `.png` classes provided by feature testing libraries such as Modernizr).

On the downside if sprites get too large some older mobiles devices might not be able to display them (due to memory limits). I haven't experienced this first hand yet though ;)

The main reason I built dr-svg-sprites was that we needed SVG sprites for our broadcasting logos at work - with fallback PNG sprites generated for each different size of logo we use.

I'm not an expert on grunticon - so AFAICT it looks like it treats each icon as separate inlined background-image in separate stylesheets for SVG/PNG and then uses a javascript loader to load the correct one when you load a page.

**Comment by Sebastian-Fitzner** [comment]
Hi, 

here a short list of facts: 

### dr-svg-sprites
- creates one sprite of icons (just one file) which you can reference and use in your css
- has one http request more for that file 
- adds png fallback as separate file 

You can animate your icons from one state to another. 

### grunticon
- inlines your icons in css (data:uri)
- does not need further request 
- has a bigger filesize (with a large set of icons you will probably bloat your css)  
- adds a png fallback as file or inline 

You can also scale these icons with `background-size` because they are not in one single file.
> ... then uses a javascript loader to load the correct one when you load a page

You do not need any js to get the right icons, you can also use classes.

#### My opinion:
*Personally I prefer to use dr-svg-sprites because:*
- I do not won't to bloat my css and then use a workaround to load the icons async
- I want to animate an icon from one state to another state

Each approach has pros and cons ;)

**Comment by ldexterldesign** [comment]
@Sebastian-Fitzner hey, cheers for the explanation and apologies for the delay - I've been out of dev' for a while. I'll explore https://github.com/drdk/grunt-dr-svg-sprites on the new project I've just started.

Would you mind if I ping this issue if I have any further questions?

Yours hopefully

**Comment by ldexterldesign** [comment]
@rasmusfl0e ditto!

**Comment by Sebastian-Fitzner** [comment]
You can ping me when you have any problems. 
You can also open a new issue, so that others can look it up and follow along. 

I have simplified the workflow by the way... Every icon has its own mixin and extend.

**Comment by ldexterldesign** [comment]
Great, I'll reference this issue when/if I need to

Kind thanks
