### ISSUE TITLE
Research updating from standard to custom install

### ISSUE THREAD

**Issue by ldexterldesign** [Prototype-Group/generator-prototype#44]
Hey,

I've just reverted to a minimal install after discovering my custom install was >500MB; leaving me unable to commit my repo' due to GitHub's 100MB file commit limit ( http://www.daisydiskapp.com/ tells me https://github.com/stefanjudis/grunt-phantomas is the culprit)

Commit etiquette aside, I'd like Foundation included in my minimal install

Is there an easy way to use the [yo] installation tool to include Foundation without me a) recreating my project as a custom install or b) configuring Grunt directly?

Would you advise getting familiar with adding/deleting Grunt.js packages sooner rather than later?

Yours hopefully

**Comment by Sebastian-Fitzner** [comment]
Hi,

first of all, do you push your node modules or bower components into your repo? Or is one generated file larger than 100MB?

But let us dicuss about extending the minimal install:

### Bower 
Your concrete example is very simple to solve, because it is a bower component. Therefore I do not integrate a sub generator, for the simple reason that you only need to install `foundation` via 
```
bower install foundation --save 
```
Then just import the files you need in `fileindex.js`, see section `sass-globbing` on http://www.prototype-generator.com/getting-started/features.html (in the next release fileindex is replaced with https://github.com/Sebastian-Fitzner/grunt-sass-globber). 

### Grunt Modules
To add further grunt packages I decided to integrate a sub generator. This generator can be started with: 
```
yo prototype:grunt 
```
The packages which can be chosen, are exactly the same as in the `custom installation` routine. 
But I have to say that it makes sense to understand the basics of grunt to adjust some settings. Just ask, when anything is not clear.

**Comment by ldexterldesign** [comment]
Hey,

Apologies for delay

Yea, I have been in the habit of pushing dependencies to repo's in the past, but I'm going to stop now and focus more on keeping an uptodate README so I can emulate the development environment in the future - thoughts?

Hmm, can you help with the following error?

<img width="1440" alt="screen shot 2015-09-03 at 01 30 14" src="https://cloud.githubusercontent.com/assets/1715809/9647254/631151c6-51db-11e5-893c-cba13bf0f9bc.png">

I'll look into Grunt modules after

Yours hopefully

**Comment by ldexterldesign** [comment]
I only just discovered my ```yo-rc.json```, so god knows how long my various experimentation builds have been referencing that ( https://github.com/yeoman/yeoman/issues/635#issuecomment-137335777 ). I also reinstalled a bunch of npm modules and cleaned cache.

Decided on a clean install so this is no longer an issue

Regards

PS However, I've come across quite a few build errors with a kitchen sink install, namely relating to JS anc QA dependencies. I gotta get a project up for a client but let me know if you'd like me to document these errors.
